- name: Stop GitLab
  ansible.builtin.command: gitlab-ctl stop

- name: Install certbot
  ansible.builtin.apt:
    name: certbot
    state: present

- name: Run certbot
  ansible.builtin.shell: |
    certbot certonly --standalone --agree-tos --email {{ cert_email }} --preferred-challenges http -d {{ external_url }} --non-interactive

- name: Backup gitlab.rb
  ansible.builtin.copy:
    src: /etc/gitlab/gitlab.rb
    dest: /etc/gitlab/gitlab.rb.bak

- name: Change gitlab config external_url
  ansible.builtin.replace:
    path: /etc/gitlab/gitlab.rb
    regexp: 'external_url\s+"http://.*?"'
    replace: 'external_url "https://{{ external_url }}"'
    backup: yes

- name: Uncomment nginx[ssl_certificate] and nginx[ssl_certificate_key]
  ansible.builtin.replace:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#\\s*(nginx\\[\\s*'ssl_certificate'\\s*\\].*)$"
    replace: '\1'
    backup: yes
  ansible.builtin.replace:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#\\s*(nginx\\[\\s*'ssl_certificate_key'\\s*\\].*)$"
    replace: '\1'

- name: Change gitlab config nginx[ssl_certificate]
  ansible.builtin.replace:
    path: /etc/gitlab/gitlab.rb
    regexp: "nginx\\['ssl_certificate'\\]\\s+\".*?\""
    replace: "nginx['ssl_certificate'] = \"/etc/letsencrypt/live/{{ external_url }}/fullchain.pem\""
  ansible.builtin.replace:
    path: /etc/gitlab/gitlab.rb
    regexp: "nginx\\['ssl_certificate_key'\\]\\s+\".*?\""
    replace: "nginx['ssl_certificate_key'] = \"/etc/letsencrypt/live/{{ external_url }}/privkey.pem\""

- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure

- name: Start GitLab
  ansible.builtin.command: gitlab-ctl start
