- name: Install Gitlab apt dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_gitlab_dependencies }}"

- name: Start runit service
  ansible.builtin.service:
    name: runit
    state: started
    enabled: yes

- name: Download Gitlab package repository install script
  ansible.builtin.uri:
    url: "{{ ubuntu_gitlab_install_script_url }}"
    dest: "{{ ubuntu_gitlab_install_script_path }}"
    mode: '0755'

- name: Install Gitlab package repository using provided script
  ansible.builtin.command: bash "{{ ubuntu_gitlab_install_script_path }}"


- name: Install Gitlab package
  ansible.builtin.apt: 
    name: gitlab-ee
    state: latest
  environment: 
    GITLAB_ROOT_EMAIL:  "{{ gitlab_root_email }}"
    GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
    EXTERNAL_URL: "{{ gitlab_external_url }}"
    AUTO_RENEW_HOUR: "{{ gitlab_ssl_auto_renew_hour }}"
    AUTO_RENEW_MINUTE: "{{ gitlab_ssl_auto_renew_minute }}"
    AUTO_RENEW_DAY_OF_MONTH: "{{ gitlab_ssl_auto_renew_day_of_month }}"

- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure

- name: Start GitLab
  ansible.builtin.command: gitlab-ctl start
