- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Install Gitlab apt dependencies
  ansible.builtin.apt:
    pkg:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - perl
      - postfix

